apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: i8843bbi6-python-gitops
  description: This is GitOps manifest for i8843bbi6-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=i8843bbi6-python
    backstage.io/kubernetes-id: i8843bbi6-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: i8843bbi6-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:i8843bbi6-python
